spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kalavastra_db?currentSchema=kalavastra
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: MyVerySecureJwtSecretKeyThatIsAtLeast32BytesLong!
    expirationMs: 3600000

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
