spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kalavastra_db?currentSchema=kalavastra
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: 'true'
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: replace_with_a_strong_random_secret_key
  expiration: 3600000   # 1 hour

server:
  port: 8081
